name: lilar_test_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Lato-Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Lato-Light
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
    - family: Lato-Medium
      fonts:
        - asset: assets/fonts/Lato-Medium.ttf
    - family: Lato-SemiBold
      fonts:
        - asset: assets/fonts/Lato-SemiBold.ttf
    - family: FlowerAppIcons
      fonts:
        - asset: assets/fonts/FlowerAppIcons.ttf